return {
  { "L3MON4D3/LuaSnip" },
  { "nvim-lua/popup.nvim" },
  { "nvim-lua/plenary.nvim" },
  { "rstacruz/vim-closer" },
  { "tpope/vim-dispatch" },
  { "iamcco/markdown-preview.nvim" },
  { "andymass/vim-matchup" },
  { "lunarvim/colorschemes" },
  { "folke/tokyonight.nvim" },
  { "lunarvim/darkplus.nvim" },
  { "hrsh7th/nvim-cmp" },
  { "hrsh7th/cmp-path" },
  { "hrsh7th/cmp-cmdline" },
  { "hrsh7th/cmp-buffer" },
  { "hrsh7th/cmp-nvim-lua" },
  { "hrsh7th/cmp-nvim-lsp" },
  { "saadparwaiz1/cmp_luasnip" },
  { "L3MON4D3/LuaSnip" },
  { "rafamadriz/friendly-snippets" },
  { "neovim/nvim-lspconfig" },
  { "williamboman/nvim-lsp-installer" },
  { "williamboman/mason.nvim" },
  { "williamboman/mason-lspconfig.nvim" },
  { "nvim-telescope/telescope.nvim" },
}
